apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: event-manager
data:
  POSTGRES_DB: temp # change value
  POSTGRES_USER: temp # change value

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: event-manager
type: Opaque
stringData:
  POSTGRES_PASSWORD: temp # change value

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: event-manager
data:
  DB_URL: jdbc:postgresql://db:5432/postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: event-manager
type: Opaque
stringData:
  DB_USERNAME: temp # change value
  DB_PASSWORD: temp # change value